### ISSUE TITLE
UI, general site prep for production, and final checklist

### ISSUE THREAD

**Issue by ivanvarghese** [tmcyf/tmcyf#4]
Various tweaks to the UI and images (notably, front page sub-content images).
- [x] Form CSS
- [x] New events
- [x] Favicon
- [x] Slider and sub-content images
- [x] Proper HTML headers
- [x] Google Analytics 
## 
- [x] Go over costs with committee
- [x] Use production keys
- [x] Upgrade Twilio account and buy number
- [x] SSL and check if all assets are served over https
- [x] Create production server or reassign current staging server
- [x] Test all possible use cases for minor, fixable bugs
- [x] Prep for demo at church
- [x] Ship dat ho
